### ISSUE TITLE
Error on exiting validator with Lodestar Gnosis client

### ISSUE THREAD

**Issue by dsimog01** [dappnode/StakingBrain#255] opened 2023-08-07 12:06 UTC
@czepluch  submitted an issue related to exiting a validator in Gnosis chain using Lodestar gnosis client + Staking Brain here: https://github.com/dappnode/DAppNodePackage-web3signer-gnosis/issues/28#issuecomment-1667615205

**Comment by dsimog01** [comment] 2023-08-07 12:07
It looks like the required lodestar config is actually included in the package: https://github.com/dappnode/StakingBrain/blob/4c45f1fd2802aa35469008e9f4e8d1397d58a5cd/packages/brain/src/modules/envs/index.ts#L180

**Comment by nflaig** [comment] 2023-08-07 14:04
I have tested voluntary exit on Goerli with Lodestar and it works there consistently, I can't test this on Gnosis chain but technically there is no difference.

@czepluch Regarding your comment https://github.com/dappnode/DAppNodePackage-web3signer-gnosis/issues/28#issuecomment-1667615205 this is kinda strange to me, I can't tell where Lodestar would throw this `PublishError.InsufficientPeersError` error. The error thrown  by Lodestar would be `PublishError.InsufficientPeers` (see [js-libp2p-gossipsub](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/3475242ed254f7647798ab7f36b21909f6cb61da/src/index.ts#L2009)), could you please check if you are connection to the correct consensus client (maybe you have multiple running).

> and I have 50 peers

Just a side note regarding peers, in theory your node can have 50 peers and not be able to publish a message as you require peers on the specific topic you want to publish on. This is very unlikely in case of `voluntary_exit` topic as the node should always have around 7-8 peers on that topic.

**Comment by nflaig** [comment] 2023-08-07 14:30
> log seems to be appending two messages without any space between them

`PublishError.InsufficientPeers` is definitely from Lodestar then, but this error should not happen consistently. Tested this locally, after few minutes of starting Gnosis Lodestar node I get 6-7 voluntary_exit topic peers.

To debug this would have to look at the the mesh peers of @czepluch, Lodestar exposes a metric to check this `lodestar_gossip_mesh_peers_by_type_count`, on dappnode metrics are enabled by default but to easily access them would have to install DMS package.

**Comment by czepluch** [comment] 2023-08-07 18:55
I've tried maybe 10 times to exit over a period of 5 hours I think. But was not successful a single time. I looked at the DMS dashboard for Lodestart Gnosis and the mesh peers there seem to be going up and down between 3 and 7.5 over the cause of the last 24 hours. Might have been 0 a couple of times, but definitely not all the times I tried to exit.

**Comment by nflaig** [comment] 2023-08-07 19:38
The [Lodestar networking dashboard](https://github.com/ChainSafe/lodestar/blob/unstable/dashboards/lodestar_networking.json) provides more details on this, but you have to import it manually.

There is a panel that shows mesh peer count by topic

![image](https://github.com/dappnode/StakingBrain/assets/38436224/0821c6f9-bca3-4058-b67d-bbd91ba3e0ac)

If you are still getting this error with sufficient peers on voluntary_exit topic I would suggest to take a look at the beacon-node logs, there should be an error log.

**Comment by pablomendezroyo** [comment] 2023-11-06 08:00
can this be closed by https://github.com/dappnode/StakingBrain/pull/260 ?

**Comment by czepluch** [comment] 2023-11-07 23:08
Yeah, I think so. Didn't check if it actually was fixed since I changed my mind and didn't exit it any way.

**Comment by pablomendezroyo** [comment] 2023-11-08 07:42
Feel free to re-open it if you still have issues exiting validators

**Closed by pablomendezroyo** 2023-11-08 07:42 UTC
